# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20170924_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='last_updated',
            field=models.DateTimeField(editable=False),
        ),
    ]
